adds pins section markup
dab82/3dfreedom pull request #27
Opened 2021-08-14 17:16 UTC by Kateryna1823

2021-08-14 18:30 UTC, AnnSamsonenko commented on src/sass/layout/_contacts-hero.scss
> +
вот тут какой то лишний плюсик

2021-08-14 18:31 UTC, AnnSamsonenko commented on src/partials/contacts-page-contacts.html
> +            </ul>
опечатка Сб, Нд: з 10:00 до 17:00

2021-08-14 18:32 UTC, AnnSamsonenko requested changes
небольшие опечатки

2021-08-15 11:38 UTC, dab82 approved these changes

2021-08-15 13:06 UTC, AnnSamsonenko approved these changes

2021-08-16 03:41 UTC, dab82 approved these changes

2021-08-16 03:41 UTC, merged